### ISSUE TITLE
This is not emacs :(((((

### ISSUE THREAD

**Issue by JKRT** [CaffeineViking/vimrc#1]
Hej Erik!

**Comment by JKRT** [comment]
https://rms.sexy 🥇 🥇 🥇 💯

**Comment by CaffeineViking** [comment]
Hej John! Emacs är bra, men varför ska man använda den när man har Vim? Då behöver man inte bli så här:

![Emacs user at work](https://i.pinimg.com/originals/6c/72/19/6c72191a6234a17d3e4e489dca847eac.jpg)
