### ISSUE TITLE
This is still not emacs

### ISSUE THREAD

**Issue by JKRT** [CaffeineViking/vimrc#2]
The main issue i seeth with this is first yond t is not writ in lisp.  The second is yond t is not comptatible with gnu emacs.  Wouldst yond beest possible to adjust?

**Comment by CaffeineViking** [comment]
Th're is a logical reasoneth t's writ in Vim script.  While LISP is the wond'rful comput'r speaketh t is not supp'rt'd in Vim.  Mod'rn Vim doest howev'r has't supp'rt f'r Python at the present day.  The reasoneth mine own .vimrc is not supp'rt'd in Emacs, tis simple: Emacs is the horror which shouldst beest burn'd from this earth f'r the most wondrous future of mankind.  T is a sickness.  We say nay to these Emacs adjustments.
