### ISSUE TITLE
This config file lacks a lisp interpreter

### ISSUE THREAD

**Issue by JKRT** [CaffeineViking/vimrc#3]
It has come to my attention that this is indeed not for Emacs. However, it seems that modern implementations of Vim do support Python as a scripting language. Therefore I think it would be very nice to include code and bindings for https://github.com/nukata/little-scheme-in-python 

By doing so we could start to provide extensions written in Lisp when people are amazed I am sure that we could extend it so that it could also function with Emacs lisp. 

I do strongly believe that such a change would enable us to make use of very nice packages for Emacs.  Ideally, we could provide a compatibility layer so that most if not all Emacs package could be used, if they would be included in this configuration I am sure this repository would be the most stared repository on Github 

Yours truly, 

John

**Comment by CaffeineViking** [comment]
*sigh*
